export const TEST_TYPE = "TEST_TYPE";
export const SOCKET_JOINING = "SOCKET_JOIN";
export const SOCKET_JOINED = "SOCKET_JOINED";
export const SOCKET_CONNECTING = "SOCKET_CONNECTING";
export const SOCKET_CONNECTED = "SOCKET_CONNECTED";